void compare() {
//  char fn0[] = "~/scratchfs/output/moonshcheck/rebase/sim_rc_all00wt_allsky.root";
  char fn0[] = "~/scratchfs/output/moonshcheck/rebase/sim_rb_all00wt_window.root";
//  char fn1[] = "/eos/lhaaso/rec/wcda/Rc/2019/1101/ES.28140.WCDA_EVENT.P1GRBM20M.20191101001721.086_rec.root";
  char fn1[] = "~/scratchfs/output/moonshcheck/rebase/window_rb/2019/1101/all.root";
  //char fn1[] = "~/scratchfs/output/moonshcheck/rebase/par_rc/2019/11xx.root";
  char tn[] = "trec";
  char drawword0[] = "azic";
  char drawword1[] = "azic";
  char drawrange[] = "(72,0,360)";
  // char selectionword0[] = "weight*(nfitc>100&&recflag1>0&&recflag2>0&&chi2c<5&&compactness>0&&type!=0)";
  char selectionword0[] = "weight*(nfitc>100&&recflag1>0&&chi2c<5&&compactness>0&&type!=0&&fabs(xc1)<40&&fabs(yc1)<40)";
  char selectionword1[] = "(1.)*(nfitc>100&&recflag>0&&chi2c<5&&omega<5&&compactness>0)";
  // char selectionword1[] = "(86400./36.233)*(nfitc>100&&recflag>0&&chi2c<5&&omega<5&&compactness>0&&fabs(xc1)<4000&&fabs(yc1)<4000)";
  TFile *f0 = new TFile(fn0);
  TTree *t0 = (TTree*)f0->Get(tn);
  TFile *f1 = new TFile(fn1);
  TTree *t1 = (TTree*)f1->Get(tn);
  TH1F *h0, *h1, *h0a, *h1a;
  t0->Draw(TString::Format("%s>>htmp0%s",drawword0,drawrange),selectionword0,"goff""");
  h0 = (TH1F*)gDirectory->Get("htmp0")->Clone();
  h0a = (TH1F*)h0->Clone();
  printf("0  ");
  t1->Draw(TString::Format("%s>>htmp1%s",drawword1,drawrange),selectionword1,"goff""");
  h1 = (TH1F*)gDirectory->Get("htmp1")->Clone();
  h1a = (TH1F*)h1->Clone();
  printf("1\n");
  printf("%e %e\n", h0->Integral(), h1->Integral());
  h0->SetLineColor(kRed);
  h0->SetMarkerColor(kRed);
  h0->SetMarkerStyle(24);
  h0->SetStats(0);
  h1->SetLineColor(kBlue);
  h1->SetMarkerColor(kBlue);
  h1->SetMarkerStyle(20);
  h1->SetStats(0);
  h0a->SetLineColor(kRed);
  h0a->SetMarkerColor(kRed);
  h0a->SetMarkerStyle(24);
  h0a->SetStats(0);
  h1a->SetLineColor(kBlue);
  h1a->SetMarkerColor(kBlue);
  h1a->SetMarkerStyle(20);
  h1a->SetStats(0);
  TCanvas *c1 = new TCanvas("c1","c1",1500,700);
  c1->Divide(2,1);
  c1->cd(1);
  double norm0 = 1.;
  double norm1 = 1.;
  h0->Scale(norm0);
  h1->Scale(norm1);
  double max = h0->GetMaximum();
  max = max > h1->GetMaximum() ? max : h1->GetMaximum();
  // double min = 1.e-3;
  double min = norm0;
  min = min < norm1 ? min : norm1;
  gPad->SetGrid();
  gPad->SetLogy();
  h0->Draw();
  h0->GetYaxis()->SetRangeUser(0.5 * min,max+fabs(max/2.));
  h1->Draw("same");
  c1->cd(2);
  norm0 = 1./h0a->Integral();
  norm1 = 1./h1a->Integral();
  printf("%e  %e\n", norm0, norm1);
  h0a->Scale(norm0);
  h1a->Scale(norm1);
  gPad->SetGrid();
  gPad->SetLogy();
  h0a->Draw();
  h1a->Draw("same");
}
